version: "3.5"
services:
  flashpaper:
    image: ghcr.io/andrewpaglusch/flashpaper:master
    container_name: flashpaper
    restart: always
    volumes:
      - './data:/var/www/html/data'
    ports:
      - '8080:80'
    environment:
      SITE_TITLE: "Paratech MSP | One-time Encryption"
      RETURN_FULL_URL: "true"
      BASE_URL: "" # https://mydomain.com/flashpaper
      MAX_SECRET_LENGTH: "3000"
      ANNOUNCEMENT: ""
      MESSAGES_ERROR_SECRET_TOO_LONG: "Input length too Encrypted Message"
      MESSAGES_SUBMIT_SECRET_SUBHEADER: ""
      MESSAGES_SUBMIT_SECRET_BUTTON: "Encrypt Message"
      MESSAGES_VIEW_CODE_HEADER: "One-Time Encrypted URL"
      MESSAGES_VIEW_CODE_SUBHEADER: "Share this URL via email, chat, or another messaging service. It will be destroyed after being viewed once."
      MESSAGES_CONFIRM_VIEW_SECRET_HEADER: "View this Secret?"
      MESSAGES_CONFIRM_VIEW_SECRET_BUTTON: "View Secret"
      MESSAGES_VIEW_SECRET_HEADER: "One-Time Encrypted Message"
      MESSAGES_VIEW_SECRET_SUBHEADER: "This message has been destroyed"
      PRUNE_ENABLED: "true"
      PRUNE_MIN_DAYS: 365
      PRUNE_MAX_DAYS: 730
      
